# Generated by Django 4.2.14 on 2024-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('Created_date',),
            },
        ),
    ]
