# Generated by Django 4.2.14 on 2024-07-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Status', models.BooleanField(default=False)),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('Created_date',),
            },
        ),
    ]
