# Generated by Django 4.2.14 on 2024-07-24 17:04

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
