# Generated by Django 4.2.14 on 2024-07-28 19:34

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=django_quill.fields.QuillField(),
        ),
    ]
